######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 8 09:24:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += declarative gui

# Input
SOURCES += main.cpp
